### PR TITLE
Add `exp` and `log` for `SoftFloat64`

### PR DESCRIPTION
**Pull request by zRedShift**
This is a draft for now since it's only implemented for `f64`, and doesn't have any tests.

### CODE REVIEW

**Comment by knickish** [comment]
@zRedShift Are you planning to continue working on this, or posting it so that someone else can finish it?

**Comment by zRedShift** [comment]
@knickish I plan to continue working on this sometime next week, shouldn't be much left. Of course, if you want to take over, I have no objections, I'm already using this code as is, I just want to upstream it, and make sure the precision is tested and there's f32 support too.

**Comment by knickish** [comment]
@zRedShift No problem, not trying to take it if you're still planning to do things with it. Appreciate the upstream.

**Comment by zRedShift** [comment]
@knickish hey, sorry, this PR this completely slipped my mind. Thanks for finishing it up and merging it 🙏

**Comment by knickish** [comment]
@zRedShift It's all good! thanks for implementing those

**Pull request merged**
